#Create and use DB
CREATE DATABASE IF NOT EXISTS MYNOTES;
USE MYNOTES;

#Create tables
CREATE TABLE IF NOT EXISTS USERS(
    USER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS NOTES(
    NOTE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(64) NOT NULL,
    TEXT VARCHAR(4096) NOT NULL,
    USER_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    PRIMARY KEY(NOTE_ID)
);